version: '3'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: food-calculate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Le26ra1703.
    volumes:
      - "db:/var/lib/postgresql/data"

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  db:
  redis: