# Generated by Django 4.1.5 on 2023-05-05 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='calorieslog',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='calorieslog',
            name='meals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.meal', verbose_name='Прием пищи'),
        ),
        migrations.AlterField(
            model_name='calorieslog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='products',
            field=models.ManyToManyField(to='web.product', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='time',
            field=models.TimeField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='product',
            name='calories_count',
            field=models.PositiveIntegerField(verbose_name='Количество калорий'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrates_count',
            field=models.PositiveIntegerField(verbose_name='Количество углеводов'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats_count',
            field=models.PositiveIntegerField(verbose_name='Количество жиров'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein_count',
            field=models.PositiveIntegerField(verbose_name='Количество белков'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(verbose_name='Вес'),
        ),
    ]
